name: demo_ecommerce_shop
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  go_router: ^14.7.2
  flutter_riverpod: ^2.6.1
  lottie: ^3.3.1
  introduction_screen: ^3.1.14
  easy_localization: ^3.0.7+1
  intl: any

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_gen_runner: ^5.9.0
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.4
  riverpod_generator: ^2.6.4
  build_runner: ^2.4.14
  custom_lint: ^0.7.2
  riverpod_lint: ^2.6.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/lotties/
    - assets/langs/

flutter_gen:
  output: lib/gen/

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
