name: demo_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter

  algolia: 1.1.2
  algoliasearch: 1.29.0
  cupertino_icons: 1.0.8
  envied: 1.1.1
  go_router: 14.7.2
  riverpod: 2.6.1
  riverpod_annotation: 2.6.1
  flutter_riverpod: 2.6.1
  lottie: 3.0.0
  introduction_screen: 3.1.14
  easy_localization: 3.0.7+1
  intl: 0.19.0
  shared_preferences: 2.5.1
  firebase_core: 3.11.0
  firebase_auth: 5.4.2
  logger: 2.5.0
  cached_network_image: 3.3.1
  cloud_firestore: 5.6.3
  equatable: 2.0.7
  firebase_storage: 12.4.2
  flutter_staggered_grid_view: 0.7.0
  flutter_stripe: 10.1.1
  flutter_stripe_web: 5.1.0
  rxdart: 0.27.7
  path_provider: 2.1.3
  pay: 2.0.0
  sembast: 3.7.1
  sembast_web: 2.3.0
  flutter_rating_bar: ^4.0.1

dependency_overrides:
  analyzer: ^6.3.0
  custom_lint_core: ^0.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: 2.4.14
  custom_lint: 0.6.4
  envied_generator: 1.1.1
  flutter_gen_runner: 5.9.0
  flutter_launcher_icons: 0.14.3
  flutter_lints: 5.0.0
  flutter_native_splash: 2.4.4
  mocktail: 1.0.3
  riverpod_generator: 2.4.0
  riverpod_lint: 2.3.10

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/lotties/
    - assets/langs/
    - assets/products/

flutter_gen:
  output: lib/gen/

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
