// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUvYGAtLE0RKD2S0WIKr6r0AQKDc5t0DM',
    appId: '1:643969335188:web:e16be5cc696634fe039981',
    messagingSenderId: '643969335188',
    projectId: 'fir-ecommerce-shop',
    authDomain: 'fir-ecommerce-shop.firebaseapp.com',
    storageBucket: 'fir-ecommerce-shop.firebasestorage.app',
    measurementId: 'G-B0SFHXFYSV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2wYEE4wzvMgqeNo_cB44Psoi7HNSmJ1c',
    appId: '1:643969335188:android:4009156cd12c0cbf039981',
    messagingSenderId: '643969335188',
    projectId: 'fir-ecommerce-shop',
    storageBucket: 'fir-ecommerce-shop.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhWFCyBqtwQR-xv3rh_CWaWJv7zRW8Mh8',
    appId: '1:643969335188:ios:df0e4daafd65e8dc039981',
    messagingSenderId: '643969335188',
    projectId: 'fir-ecommerce-shop',
    storageBucket: 'fir-ecommerce-shop.firebasestorage.app',
    iosBundleId: 'com.example.demoEcommerceShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhWFCyBqtwQR-xv3rh_CWaWJv7zRW8Mh8',
    appId: '1:643969335188:ios:df0e4daafd65e8dc039981',
    messagingSenderId: '643969335188',
    projectId: 'fir-ecommerce-shop',
    storageBucket: 'fir-ecommerce-shop.firebasestorage.app',
    iosBundleId: 'com.example.demoEcommerceShop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUvYGAtLE0RKD2S0WIKr6r0AQKDc5t0DM',
    appId: '1:643969335188:web:cc9407694c5341aa039981',
    messagingSenderId: '643969335188',
    projectId: 'fir-ecommerce-shop',
    authDomain: 'fir-ecommerce-shop.firebaseapp.com',
    storageBucket: 'fir-ecommerce-shop.firebasestorage.app',
    measurementId: 'G-X0F0ND5XQ4',
  );
}
